output_dir: "/home/yinh4/DENSPOUT/outputs-fabric"
seed: 1234

# Model parameters
model: "vanilla_gan"
nz: 100
ngf: 64
ndf: 64

# Optimizer parameters
lr: 0.0002
beta1: 0.5

# Data parameters
dataroot: "/home/yinh4/DENSPOUT/data/"
image_size: 64
workers: 128
nc: 3

# Training parameters
batch_size: 4
num_epochs: 100
gpu_nums: "2,3"
print_every: 50
save_every: 500
ckpt_dir: "/home/yinh4/DENSPOUT/ckpt_dir"
ckpt_name: null



